root = "."

tmp_dir = "./tmp"
testdata_dir = "testdata"

[build]
delay = 1000
stop_on_error = true

include_ext = ["go", "tpl", "tmpl", "html", "sql", "yaml", "graphql"]
include_file = [".env.local"]
exclude_dir = ["assets", "tmp", "vendor", "testdata", "internal/repository"]
exclude_file = ["internal/infra/client/anilist/graphql/generated.go"]
exclude_regex = ["_test.go"]

send_interrupt = true
kill_delay = "500ms"

log = "build-errors.log"

[log]
main_only = false
silent = false
time = true

[screen]
clear_on_rebuild = true
keep_scroll = true
