services:
  traefik:
    image: traefik:v3.1
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aniways_net

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - aniways_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - postgres_password

  redis:
    image: ghcr.io/coeeter/aniways-redis:latest
    volumes:
      - redis_data:/data
    networks:
      - aniways_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - redis_password

  api:
    image: ghcr.io/coeeter/aniways-api:latest
    networks:
      - aniways_net
    depends_on:
      - db
      - redis
    secrets:
      - aniways_env
    environment:
      - ENV_FILE_PATH=/run/secrets/aniways_env
    labels:
      - traefik.enable=true
      - traefik.http.services.api.loadbalancer.server.port=8080
      - traefik.http.routers.api.rule=Host(`${API_DOMAIN}`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=myresolver
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  worker:
    image: ghcr.io/coeeter/aniways-worker:latest
    networks:
      - aniways_net
    depends_on:
      - db
      - redis
    secrets:
      - aniways_env
    environment:
      - ENV_FILE_PATH=/run/secrets/aniways_env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  proxy:
    image: ghcr.io/coeeter/aniways-proxy:latest
    networks:
      - aniways_net
    labels:
      - traefik.enable=true
      - traefik.http.services.proxy.loadbalancer.server.port=1234
      - traefik.http.routers.proxy.rule=Host(`${PROXY_DOMAIN}`)
      - traefik.http.routers.proxy.entrypoints=websecure
      - traefik.http.routers.proxy.tls.certresolver=myresolver
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

volumes:
  letsencrypt:
  db_data:
  redis_data:

networks:
  aniways_net:
    driver: overlay

secrets:
  postgres_password:
    external: true
  redis_password:
    external: true
  aniways_env:
    external: true
